[package]
name = "spin_wheel_game"
version = "0.1.0"
authors = ["Jason Schein <jasonschein@gmail.com>"]
build = "build.rs"

[dependencies]
piston = "0.10.0"
piston_window = "0.16.0"
rand = "0.3.1"
pistoncore-sdl2_window = "0.12.0"